name: Activities
description: View your Activities where ever you go.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  http: ^0.12.1
  qrscan: ^0.2.21
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.4+1
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.12+4
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
